/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as SponsorRouteImport } from './routes/_sponsor'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentDiscoverRouteImport } from './routes/_student/discover'
import { Route as SponsorScholarshipsRouteImport } from './routes/_sponsor/scholarships'
import { Route as SponsorCreateRouteImport } from './routes/_sponsor/create'
import { Route as OnboardingWelcomeRouteImport } from './routes/_onboarding/welcome'
import { Route as OnboardingRoleSelectionRouteImport } from './routes/_onboarding/role-selection'
import { Route as OnboardingProfileSetupRouteImport } from './routes/_onboarding/profile-setup'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as StudentHomeIndexRouteImport } from './routes/_student/home/index'
import { Route as LandingAboutIndexRouteImport } from './routes/_landing/about/index'
import { Route as StudentScholarshipIdApplyRouteImport } from './routes/_student/scholarship/$id/apply'
import { Route as StudentProfileStudentStudentIdRouteImport } from './routes/_student/profile/student/$studentId'
import { Route as SponsorScholarshipIdEditRouteImport } from './routes/_sponsor/scholarship/$id/edit'
import { Route as SponsorScholarshipIdApplicantsRouteImport } from './routes/_sponsor/scholarship/$id/applicants'
import { Route as SponsorProfileSponsorSponsorIdRouteImport } from './routes/_sponsor/profile/sponsor/$sponsorId'

const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/_sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDiscoverRoute = StudentDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => StudentRoute,
} as any)
const SponsorScholarshipsRoute = SponsorScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => SponsorRoute,
} as any)
const SponsorCreateRoute = SponsorCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SponsorRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleSelectionRoute = OnboardingRoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileSetupRoute = OnboardingProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const StudentHomeIndexRoute = StudentHomeIndexRouteImport.update({
  id: '/home/',
  path: '/home/',
  getParentRoute: () => StudentRoute,
} as any)
const LandingAboutIndexRoute = LandingAboutIndexRouteImport.update({
  id: '/_landing/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentScholarshipIdApplyRoute =
  StudentScholarshipIdApplyRouteImport.update({
    id: '/scholarship/$id/apply',
    path: '/scholarship/$id/apply',
    getParentRoute: () => StudentRoute,
  } as any)
const StudentProfileStudentStudentIdRoute =
  StudentProfileStudentStudentIdRouteImport.update({
    id: '/profile/student/$studentId',
    path: '/profile/student/$studentId',
    getParentRoute: () => StudentRoute,
  } as any)
const SponsorScholarshipIdEditRoute =
  SponsorScholarshipIdEditRouteImport.update({
    id: '/scholarship/$id/edit',
    path: '/scholarship/$id/edit',
    getParentRoute: () => SponsorRoute,
  } as any)
const SponsorScholarshipIdApplicantsRoute =
  SponsorScholarshipIdApplicantsRouteImport.update({
    id: '/scholarship/$id/applicants',
    path: '/scholarship/$id/applicants',
    getParentRoute: () => SponsorRoute,
  } as any)
const SponsorProfileSponsorSponsorIdRoute =
  SponsorProfileSponsorSponsorIdRouteImport.update({
    id: '/profile/sponsor/$sponsorId',
    path: '/profile/sponsor/$sponsorId',
    getParentRoute: () => SponsorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/create': typeof SponsorCreateRoute
  '/scholarships': typeof SponsorScholarshipsRoute
  '/discover': typeof StudentDiscoverRoute
  '/about': typeof LandingAboutIndexRoute
  '/home': typeof StudentHomeIndexRoute
  '/profile/sponsor/$sponsorId': typeof SponsorProfileSponsorSponsorIdRoute
  '/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditRoute
  '/profile/student/$studentId': typeof StudentProfileStudentStudentIdRoute
  '/scholarship/$id/apply': typeof StudentScholarshipIdApplyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/create': typeof SponsorCreateRoute
  '/scholarships': typeof SponsorScholarshipsRoute
  '/discover': typeof StudentDiscoverRoute
  '/about': typeof LandingAboutIndexRoute
  '/home': typeof StudentHomeIndexRoute
  '/profile/sponsor/$sponsorId': typeof SponsorProfileSponsorSponsorIdRoute
  '/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditRoute
  '/profile/student/$studentId': typeof StudentProfileStudentStudentIdRoute
  '/scholarship/$id/apply': typeof StudentScholarshipIdApplyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_sponsor': typeof SponsorRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_onboarding/profile-setup': typeof OnboardingProfileSetupRoute
  '/_onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/_onboarding/welcome': typeof OnboardingWelcomeRoute
  '/_sponsor/create': typeof SponsorCreateRoute
  '/_sponsor/scholarships': typeof SponsorScholarshipsRoute
  '/_student/discover': typeof StudentDiscoverRoute
  '/_landing/about/': typeof LandingAboutIndexRoute
  '/_student/home/': typeof StudentHomeIndexRoute
  '/_sponsor/profile/sponsor/$sponsorId': typeof SponsorProfileSponsorSponsorIdRoute
  '/_sponsor/scholarship/$id/applicants': typeof SponsorScholarshipIdApplicantsRoute
  '/_sponsor/scholarship/$id/edit': typeof SponsorScholarshipIdEditRoute
  '/_student/profile/student/$studentId': typeof StudentProfileStudentStudentIdRoute
  '/_student/scholarship/$id/apply': typeof StudentScholarshipIdApplyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
    | '/create'
    | '/scholarships'
    | '/discover'
    | '/about'
    | '/home'
    | '/profile/sponsor/$sponsorId'
    | '/scholarship/$id/applicants'
    | '/scholarship/$id/edit'
    | '/profile/student/$studentId'
    | '/scholarship/$id/apply'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
    | '/create'
    | '/scholarships'
    | '/discover'
    | '/about'
    | '/home'
    | '/profile/sponsor/$sponsorId'
    | '/scholarship/$id/applicants'
    | '/scholarship/$id/edit'
    | '/profile/student/$studentId'
    | '/scholarship/$id/apply'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_onboarding'
    | '/_sponsor'
    | '/_student'
    | '/_auth/login'
    | '/_auth/register'
    | '/_onboarding/profile-setup'
    | '/_onboarding/role-selection'
    | '/_onboarding/welcome'
    | '/_sponsor/create'
    | '/_sponsor/scholarships'
    | '/_student/discover'
    | '/_landing/about/'
    | '/_student/home/'
    | '/_sponsor/profile/sponsor/$sponsorId'
    | '/_sponsor/scholarship/$id/applicants'
    | '/_sponsor/scholarship/$id/edit'
    | '/_student/profile/student/$studentId'
    | '/_student/scholarship/$id/apply'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SponsorRoute: typeof SponsorRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  LandingAboutIndexRoute: typeof LandingAboutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sponsor': {
      id: '/_sponsor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/discover': {
      id: '/_student/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof StudentDiscoverRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarships': {
      id: '/_sponsor/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof SponsorScholarshipsRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/create': {
      id: '/_sponsor/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof SponsorCreateRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_onboarding/welcome': {
      id: '/_onboarding/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/role-selection': {
      id: '/_onboarding/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof OnboardingRoleSelectionRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/profile-setup': {
      id: '/_onboarding/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof OnboardingProfileSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_student/home/': {
      id: '/_student/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof StudentHomeIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_landing/about/': {
      id: '/_landing/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof LandingAboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/scholarship/$id/apply': {
      id: '/_student/scholarship/$id/apply'
      path: '/scholarship/$id/apply'
      fullPath: '/scholarship/$id/apply'
      preLoaderRoute: typeof StudentScholarshipIdApplyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_student/profile/student/$studentId': {
      id: '/_student/profile/student/$studentId'
      path: '/profile/student/$studentId'
      fullPath: '/profile/student/$studentId'
      preLoaderRoute: typeof StudentProfileStudentStudentIdRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarship/$id/edit': {
      id: '/_sponsor/scholarship/$id/edit'
      path: '/scholarship/$id/edit'
      fullPath: '/scholarship/$id/edit'
      preLoaderRoute: typeof SponsorScholarshipIdEditRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/scholarship/$id/applicants': {
      id: '/_sponsor/scholarship/$id/applicants'
      path: '/scholarship/$id/applicants'
      fullPath: '/scholarship/$id/applicants'
      preLoaderRoute: typeof SponsorScholarshipIdApplicantsRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/profile/sponsor/$sponsorId': {
      id: '/_sponsor/profile/sponsor/$sponsorId'
      path: '/profile/sponsor/$sponsorId'
      fullPath: '/profile/sponsor/$sponsorId'
      preLoaderRoute: typeof SponsorProfileSponsorSponsorIdRouteImport
      parentRoute: typeof SponsorRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingProfileSetupRoute: typeof OnboardingProfileSetupRoute
  OnboardingRoleSelectionRoute: typeof OnboardingRoleSelectionRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingProfileSetupRoute: OnboardingProfileSetupRoute,
  OnboardingRoleSelectionRoute: OnboardingRoleSelectionRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SponsorRouteChildren {
  SponsorCreateRoute: typeof SponsorCreateRoute
  SponsorScholarshipsRoute: typeof SponsorScholarshipsRoute
  SponsorProfileSponsorSponsorIdRoute: typeof SponsorProfileSponsorSponsorIdRoute
  SponsorScholarshipIdApplicantsRoute: typeof SponsorScholarshipIdApplicantsRoute
  SponsorScholarshipIdEditRoute: typeof SponsorScholarshipIdEditRoute
}

const SponsorRouteChildren: SponsorRouteChildren = {
  SponsorCreateRoute: SponsorCreateRoute,
  SponsorScholarshipsRoute: SponsorScholarshipsRoute,
  SponsorProfileSponsorSponsorIdRoute: SponsorProfileSponsorSponsorIdRoute,
  SponsorScholarshipIdApplicantsRoute: SponsorScholarshipIdApplicantsRoute,
  SponsorScholarshipIdEditRoute: SponsorScholarshipIdEditRoute,
}

const SponsorRouteWithChildren =
  SponsorRoute._addFileChildren(SponsorRouteChildren)

interface StudentRouteChildren {
  StudentDiscoverRoute: typeof StudentDiscoverRoute
  StudentHomeIndexRoute: typeof StudentHomeIndexRoute
  StudentProfileStudentStudentIdRoute: typeof StudentProfileStudentStudentIdRoute
  StudentScholarshipIdApplyRoute: typeof StudentScholarshipIdApplyRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDiscoverRoute: StudentDiscoverRoute,
  StudentHomeIndexRoute: StudentHomeIndexRoute,
  StudentProfileStudentStudentIdRoute: StudentProfileStudentStudentIdRoute,
  StudentScholarshipIdApplyRoute: StudentScholarshipIdApplyRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SponsorRoute: SponsorRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  LandingAboutIndexRoute: LandingAboutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
