/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingWelcomeRouteImport } from './routes/_onboarding/welcome'
import { Route as OnboardingRoleSelectionRouteImport } from './routes/_onboarding/role-selection'
import { Route as OnboardingProfileSetupRouteImport } from './routes/_onboarding/profile-setup'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleSelectionRoute = OnboardingRoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileSetupRoute = OnboardingProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_onboarding/profile-setup': typeof OnboardingProfileSetupRoute
  '/_onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/_onboarding/welcome': typeof OnboardingWelcomeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_onboarding'
    | '/_auth/login'
    | '/_auth/register'
    | '/_onboarding/profile-setup'
    | '/_onboarding/role-selection'
    | '/_onboarding/welcome'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding/welcome': {
      id: '/_onboarding/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/role-selection': {
      id: '/_onboarding/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof OnboardingRoleSelectionRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/profile-setup': {
      id: '/_onboarding/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof OnboardingProfileSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingProfileSetupRoute: typeof OnboardingProfileSetupRoute
  OnboardingRoleSelectionRoute: typeof OnboardingRoleSelectionRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingProfileSetupRoute: OnboardingProfileSetupRoute,
  OnboardingRoleSelectionRoute: OnboardingRoleSelectionRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
