/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentRouteImport } from './routes/_student'
import { Route as SponsorRouteImport } from './routes/_sponsor'
import { Route as OnboardingRouteImport } from './routes/_onboarding'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentDiscoverRouteImport } from './routes/_student/discover'
import { Route as SponsorScholarshipsRouteImport } from './routes/_sponsor/scholarships'
import { Route as SponsorCreateRouteImport } from './routes/_sponsor/create'
import { Route as OnboardingWelcomeRouteImport } from './routes/_onboarding/welcome'
import { Route as OnboardingRoleSelectionRouteImport } from './routes/_onboarding/role-selection'
import { Route as OnboardingProfileSetupRouteImport } from './routes/_onboarding/profile-setup'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as SponsorScholarshipIdEditRouteImport } from './routes/_sponsor/scholarship/$id/edit'

const StudentRoute = StudentRouteImport.update({
  id: '/_student',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorRoute = SponsorRouteImport.update({
  id: '/_sponsor',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/_onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentDiscoverRoute = StudentDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => StudentRoute,
} as any)
const SponsorScholarshipsRoute = SponsorScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => SponsorRoute,
} as any)
const SponsorCreateRoute = SponsorCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => SponsorRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingRoleSelectionRoute = OnboardingRoleSelectionRouteImport.update({
  id: '/role-selection',
  path: '/role-selection',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingProfileSetupRoute = OnboardingProfileSetupRouteImport.update({
  id: '/profile-setup',
  path: '/profile-setup',
  getParentRoute: () => OnboardingRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const SponsorScholarshipIdEditRoute =
  SponsorScholarshipIdEditRouteImport.update({
    id: '/scholarship/$id/edit',
    path: '/scholarship/$id/edit',
    getParentRoute: () => SponsorRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/create': typeof SponsorCreateRoute
  '/scholarships': typeof SponsorScholarshipsRoute
  '/discover': typeof StudentDiscoverRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/profile-setup': typeof OnboardingProfileSetupRoute
  '/role-selection': typeof OnboardingRoleSelectionRoute
  '/welcome': typeof OnboardingWelcomeRoute
  '/create': typeof SponsorCreateRoute
  '/scholarships': typeof SponsorScholarshipsRoute
  '/discover': typeof StudentDiscoverRoute
  '/scholarship/$id/edit': typeof SponsorScholarshipIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_onboarding': typeof OnboardingRouteWithChildren
  '/_sponsor': typeof SponsorRouteWithChildren
  '/_student': typeof StudentRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_onboarding/profile-setup': typeof OnboardingProfileSetupRoute
  '/_onboarding/role-selection': typeof OnboardingRoleSelectionRoute
  '/_onboarding/welcome': typeof OnboardingWelcomeRoute
  '/_sponsor/create': typeof SponsorCreateRoute
  '/_sponsor/scholarships': typeof SponsorScholarshipsRoute
  '/_student/discover': typeof StudentDiscoverRoute
  '/_sponsor/scholarship/$id/edit': typeof SponsorScholarshipIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
    | '/create'
    | '/scholarships'
    | '/discover'
    | '/scholarship/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/profile-setup'
    | '/role-selection'
    | '/welcome'
    | '/create'
    | '/scholarships'
    | '/discover'
    | '/scholarship/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_onboarding'
    | '/_sponsor'
    | '/_student'
    | '/_auth/login'
    | '/_auth/register'
    | '/_onboarding/profile-setup'
    | '/_onboarding/role-selection'
    | '/_onboarding/welcome'
    | '/_sponsor/create'
    | '/_sponsor/scholarships'
    | '/_student/discover'
    | '/_sponsor/scholarship/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
  SponsorRoute: typeof SponsorRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_student': {
      id: '/_student'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_sponsor': {
      id: '/_sponsor'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof SponsorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_onboarding': {
      id: '/_onboarding'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_student/discover': {
      id: '/_student/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof StudentDiscoverRouteImport
      parentRoute: typeof StudentRoute
    }
    '/_sponsor/scholarships': {
      id: '/_sponsor/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof SponsorScholarshipsRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_sponsor/create': {
      id: '/_sponsor/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof SponsorCreateRouteImport
      parentRoute: typeof SponsorRoute
    }
    '/_onboarding/welcome': {
      id: '/_onboarding/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/role-selection': {
      id: '/_onboarding/role-selection'
      path: '/role-selection'
      fullPath: '/role-selection'
      preLoaderRoute: typeof OnboardingRoleSelectionRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_onboarding/profile-setup': {
      id: '/_onboarding/profile-setup'
      path: '/profile-setup'
      fullPath: '/profile-setup'
      preLoaderRoute: typeof OnboardingProfileSetupRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_sponsor/scholarship/$id/edit': {
      id: '/_sponsor/scholarship/$id/edit'
      path: '/scholarship/$id/edit'
      fullPath: '/scholarship/$id/edit'
      preLoaderRoute: typeof SponsorScholarshipIdEditRouteImport
      parentRoute: typeof SponsorRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface OnboardingRouteChildren {
  OnboardingProfileSetupRoute: typeof OnboardingProfileSetupRoute
  OnboardingRoleSelectionRoute: typeof OnboardingRoleSelectionRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingProfileSetupRoute: OnboardingProfileSetupRoute,
  OnboardingRoleSelectionRoute: OnboardingRoleSelectionRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface SponsorRouteChildren {
  SponsorCreateRoute: typeof SponsorCreateRoute
  SponsorScholarshipsRoute: typeof SponsorScholarshipsRoute
  SponsorScholarshipIdEditRoute: typeof SponsorScholarshipIdEditRoute
}

const SponsorRouteChildren: SponsorRouteChildren = {
  SponsorCreateRoute: SponsorCreateRoute,
  SponsorScholarshipsRoute: SponsorScholarshipsRoute,
  SponsorScholarshipIdEditRoute: SponsorScholarshipIdEditRoute,
}

const SponsorRouteWithChildren =
  SponsorRoute._addFileChildren(SponsorRouteChildren)

interface StudentRouteChildren {
  StudentDiscoverRoute: typeof StudentDiscoverRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentDiscoverRoute: StudentDiscoverRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
  SponsorRoute: SponsorRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
